language: python
python:        
  - "3.5"

notifications:
  email: false

install:
  - pip install python-coveralls
  - pip install termcolor

script: coverage run test_rpn.py

after_success:
  - coveralls